# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_tutorial',
                'doc_host': 'https://hoangtrung020541.github.io',
                'git_url': 'https://github.com/hoangtrung020541/nbdev_tutorial',
                'lib_path': 'nbdev_tutorial'},
  'syms': {'nbdev_tutorial.test': {'nbdev_tutorial.test.test': ('test.html#test', 'nbdev_tutorial/test.py')}}}
